apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prism-pipe.fullname" . }}-config
  labels:
    {{- include "prism-pipe.labels" . | nindent 4 }}
data:
  prism-pipe.yaml: |
    port: {{ .Values.config.port | default 3000 }}
    logLevel: {{ .Values.config.logLevel | default "info" }}
    requestTimeout: {{ .Values.config.requestTimeout | default 120000 }}
